### PR TITLE
[PR] Fix tests to support use of a default branch that is not "master"

### PR DESCRIPTION
**Pull request by falken42**
Three tests currently fail if the global default branch (`init.defaultbranch`) for git is set to use something other than `master`:

```
falken@mbp-ubuntu:~/src/git-subrepo$ uname -a
Linux mbp-ubuntu 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
falken@mbp-ubuntu:~/src/git-subrepo$ git --version
git version 2.30.0
falken@mbp-ubuntu:~/src/git-subrepo$ git config --global -l | grep defaultbranch
init.defaultbranch=main
falken@mbp-ubuntu:~/src/git-subrepo$ make test
prove  test/
test/branch-all.t ................ ok   
[...]
test/init.t ...................... ok    
test/issue29.t ................... git-subrepo: Command failed: 'git fetch --no-tags --quiet ../share master'.
fatal: couldn't find remote ref master
test/issue29.t ................... No subtests run 
test/issue95.t ................... No subtests run 
test/issue96.t ................... 1/? #   Failed test at test/issue96.t line 83.
#     got: 'Subrepo 'sub' pulled from '../sub' (main).'
#   expected: 'Subrepo 'sub' pulled from '../sub' (master).'
test/issue96.t ................... Failed 1/2 subtests 
test/pull-all.t .................. ok   
[...] 
test/submodule.t ................. ok   

Test Summary Report
-------------------
test/issue29.t                 (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
test/issue95.t                 (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
test/issue96.t                 (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  1
Files=36, Tests=375, 47 wallclock secs ( 0.09 usr  0.06 sys + 35.07 cusr 11.11 csys = 46.33 CPU)
Result: FAIL
make: *** [Makefile:50: test] Error 1
```

By first retrieving any globally configured default branch (using `master` as a fallback if none is set), and using that branch name for the affected tests, all tests now successfully pass:

```
falken@mbp-ubuntu:~/src/git-subrepo$ git config --global -l | grep defaultbranch
init.defaultbranch=main
falken@mbp-ubuntu:~/src/git-subrepo$ make test
prove  test/
test/branch-all.t ................ ok   
[...]
test/init.t ...................... ok    
test/issue29.t ................... ok   
test/issue95.t ................... ok   
test/issue96.t ................... ok   
test/pull-all.t .................. ok   
[...]
test/submodule.t ................. ok   
All tests successful.
Files=36, Tests=378, 56 wallclock secs ( 0.13 usr  0.05 sys + 41.32 cusr 14.97 csys = 56.47 CPU)
Result: PASS
```

### CODE REVIEW

**Comment by admorgan** [comment]
In principle I don't have a problem with this change, but since master is currently the default is there a bigger purpose?

**Comment by falken42** [comment]
It's intended to ensure the tests work as expected for anyone who runs them.

I only noticed this because I have the default branch set to `main`, and I wanted to make sure the tests executed properly before I began making any modifications to git-subrepo.

**Comment by admorgan** [comment]
If you put this on the release/0.4.5 branch I will merge it.

**Comment by falken42** [comment]
Done.  Thank you!

**Pull request merged**
