### PR TITLE
Allow symbolic linking of git-subrepo script.

### LINKED ISSUE #75: Allow symlinking git-subrepo
I'm trying to create a Homebrew formula for git-subrepo at https://github.com/Homebrew/homebrew/pull/38158. Installing the non-executable `bash+.bash` file to `bin` will not pass their audit. This is the file that is sourced by the `git-subrepo` script.

The solution should for me to install the script and its helper to `libexec`, creating a symbolic link to `git-subrepo` from `bin`. However, this does not work, since the script uses `BASH_SOURCE` to source its helper. An example of how to solve this: http://stackoverflow.com/a/246128/596329

### PR DESCRIPTION
**Pull request by a1russell**
Should fix #75.

### CODE REVIEW

**Comment by a1russell** [comment]
Any feedback on this?

**Comment by a1russell** [comment]
Any feedback on this?

**Comment by ingydotnet** [comment]
Sorry. Been travelling. I'll look at this in the next days. It seems fine.

**Comment by a1russell** [comment]
I've also been traveling. :-) Have you had a chance to look, yet?

**Comment by a1russell** [comment]
I know you're still alive from your GitHub activity. Any feedback on this yet?

**Comment by a1russell** [comment]
Pinging yet again.

**Comment by ingydotnet** [comment]
@a1russell, thanks for sticking with this. I've applied the patch. If it works,
please close issues #75 and #76.

Cheers!

**Comment by ingydotnet** [comment]
@a1russell Also let me know if you want me to tag a release for this.

**Comment by a1russell** [comment]
Thanks @ingydotnet! Yes, a release would be helpful.

**Comment by ingydotnet** [comment]
Updated versions and tagged 0.2.3

**Comment by a1russell** [comment]
Thanks!

**Pull request closed without merging**
