### PR TITLE
add per command help

### PR DESCRIPTION
**Pull request by perlpunk**
see issue #28

### CODE REVIEW

**Comment by ingydotnet** [comment]
@perlpunk, thanks for the PR. 2 things:

- It breaks test/subrepo-branch-all.t
- In `git-hub` when you type in the wrong cli args if shows the command help
  after the error.

I'll take a quick look and see if I can resolve them.

**Comment by perlpunk** [comment]
oops, sorry, got the string comparison wrong.
`s/-ne/!=/`
pushed.

**Comment by perlpunk** [comment]
i added the usage output in case of an error

**Comment by ingydotnet** [comment]
Cool. I'll release with that.

I got the error messaging working but I think it is too noisy. Will create a
new issue, and push to a branch.

**Comment by ingydotnet** [comment]
Applied. Pushed. Thanks!

I'll hold off on the error message stuff and start a new issue.

**Pull request closed without merging**
