### PR TITLE
Improve instructions for resolving conflicts

### PR DESCRIPTION
**Pull request by jrosdahl**
Here's an improved version of my sketch in #121 in code form.

Confession: I haven't tried the push failure case since I don't understand how to reach that code path (is it even possible?).

### CODE REVIEW

**Comment by ingydotnet** [comment]
Thank you @jrosdahl.

I'll try it out. Do you know a simple way to create a pull and a push conflict?

**Comment by grimmySwe** [comment]
@ingydotnet I think you can look at test cases like pull-ours.t to find cases where you get conflicts.

@jrosdahl I agree that the push case is currently unreachable. Current workflow is that unless you use --force you must pull before you are allowed to push, so that you will get the conflicts during that step. When you push you push with the theirs flag so you don't get conflicts.

**Comment by ingydotnet** [comment]
Found a way to repro:

    git subrepo pull ext/bashplus -b 25c1dc85d50a7e25c896938ec03b22120b2eb414

which is an earlier commit on the subrepo.

I reviewed this, adjusted some wording, and will now push it.

**Comment by ingydotnet** [comment]
Applied. Thanks!

@grimmySwe et al, here is how I applied this PR (and all PRs) using
https://github.com/ingydotnet/git-hub

    > git checkout master
    > git pull --ff-only
    > git hub pr-list
    > git hub pr-fetch 126
    > git checkout PR/126
    > git rebase master
    > # Review, test, adjust, commit
    > git checkout master
    > git rebase PR/126
    > make test
    > git push

This keeps the history flat and clean, and is a pretty great way (imho) to work
with PRs.

**Pull request closed without merging**
