### PR TITLE
Added (very) basic fish support

### PR DESCRIPTION
**Pull request by ErikBjare**
Slight progress on https://github.com/ingydotnet/git-subrepo/issues/187.

Doesn't do autocompletion, but the other stuff works.

By the way, thanks @ingydotnet for working on this project! 

Hopeful it will be of use for my ActivityWatch project (see this issue: https://github.com/ActivityWatch/activitywatch/issues/70).

### CODE REVIEW

**Comment by ingydotnet** [comment]
@ErikBjare thank you for this. We will look at adding it after the upcoming 0.4.0 release work is done. It might even make it into the release.

**Comment by milieu** [comment]
:(

**Comment by ingydotnet** [comment]
Can you target this PR against master? The `release/0.4.0` branch has now been merged.

**Comment by ErikBjare** [comment]
@ingydotnet Done

**Comment by nvh** [comment]
What is the current status on this, and how can I help land this PR?

**Comment by ErikBjare** [comment]
I'm not interested in this issue anymore, as we went with another approach to managing out git repos.

Anyone who feels like it is free to continue the work.

**Comment by admorgan** [comment]
Committed in #446

**Pull request closed without merging**
