### PR TITLE
subrepo init should complete to directories, not existing subrepos

### PR DESCRIPTION
**Pull request by perlpunk**
see #148

### CODE REVIEW

**Comment by ingydotnet** [comment]
@perlpunk, this works but it completes to files as well as directories. It
should really only complete to non-empty directories. And maybe also only to
dirs without a .gitrepo subdir.

**Comment by perlpunk** [comment]
This might take a while. Right now it's just using the default completion for bash, which is file completion.
I'd have to reimplement the builtin file completion.
You might want to merge this for now and create a new issue...

**Comment by ingydotnet** [comment]
sounds good

**Comment by ingydotnet** [comment]
Applied. Pushed. Thanks!

**Pull request closed without merging**
