### PR TITLE
Issue/107 + with fixes for #106, #107, #108, #109

### PR DESCRIPTION
**Pull request by grimmySwe**
Here some fixes for problems:
#106 #107 #108 #109

@ingydotnet Even if you don't do a new release it might be got to merge it to master so it easier to verify them and people that clone out master get the top branch.

### CODE REVIEW

**Comment by ingydotnet** [comment]
@grimmySwe sorry to just be getting to this.

I've pushed this as issue/110 branch.

The one thing I'm not fond of is the --list option for the merge-base command. I
don't like is because it's  only for a single command.

Two possible solutions come to mind.

1) Use the `--all` flag instead since the normal meaning doesn't apply to
merge-base.

2) Use a special environment variable.

I'd go with the first one. In either case, you need to update the merge-base
doc in `doc/git-subrepo.swim`.

**Comment by ingydotnet** [comment]
@grimmySwe, see 639a002 for a possible patch.

Also, I've lost track. What other issues would #110 close?

**Comment by grimmySwe** [comment]
@ingydotnet I totally agree with your suggestion of using --all instead of --list, it is much better and consistent. 

Issues fixed in this is #106, #107, #108, #109, #110.

I am away on holiday so I can't perform any real tests but your suggested patch looks good to me.

**Comment by ingydotnet** [comment]
Merged to master with fixes.

@grimmySwe, I'd like to make this into a release in early January. Give things
a review when you are back in action.

I'll close #106 #107 #108 #109 for now as well.

**Pull request closed without merging**
