### PR TITLE
#163 New status functionality

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by robe070** [comment]
I applied `stsquared99/master-show` to branch `issue/142`. The error `missing branch ref ` is displayed. See below. The Tracking Branch exists. I haven't performed any `subrepo push` or `subrepo pull` commands which do anything as the subrepos are up to date. Maybe the missing branch ref is due to that? How can I check what is missing?

```
$ git subrepo status lansa/imports/DEMOAPP
Git subrepo 'lansa/imports/DEMOAPP':
  Status not available: missing branch ref.
    (use 'git subrepo branch' to update)

See also: git subrepo show ...
$ git subrepo show lansa/imports/DEMOAPP
Git subrepo 'lansa/imports/DEMOAPP':
  Remote Name:     subrepo/lansa/imports/DEMOAPP
  Remote URL:      vl_demoapp-git@gitsrv:/home/git-repo/vl_demoapp.git
  Upstream Ref:    75cf530
  Tracking Branch: trunk
  Pulled Commit:   75cf530
  Pull Parent:     f96897b
```

**Comment by robe070** [comment]
And the tests fail too:
```
test/status.t ............... 4/? C:\dev\git\git-subrepo\lib\git-subrepo: line 886: subrepo:merge-base: command not found
test/status.t ............... 5/? #   Failed test 'subrepo status (up-to-date) output is correct'
#   at test/status.t line 42.
#     got: 'Git subrepo 'bar':
#   Status not available: no common ancestor found
#
# See also: git subrepo show ...'
#   expected: 'Git subrepo 'bar':
#   Subrepo is up-to-date with upstream.
#
# See also: git subrepo show ...'
C:\dev\git\git-subrepo\lib\git-subrepo: line 886: subrepo:merge-base: command not found
test/status.t ............... 6/? #   Failed test 'subrepo status (quiet) output is correct'
#   at test/status.t line 54.
#     got: 'Git subrepo 'bar':
#   Status not available: no common ancestor found
#
# See also: git subrepo show ...'
#   expected: 'See also: git subrepo show ...'
test/status.t ............... 7/? C:\dev\git\git-subrepo\lib\git-subrepo: line 886: subrepo:merge-base: command not found
test/status.t ............... 8/? #   Failed test 'subrepo status (ahead, post-commit) output is correct'
#   at test/status.t line 72.
#     got: 'Git subrepo 'bar':
#   Status not available: no common ancestor found
#
# See also: git subrepo show ...'
#   expected: 'Git subrepo 'bar':
#   Subrepo is ahead of upstream.
#     (use 'git subrepo push' to publish your local commits)
#
# See also: git subrepo show ...'
test/status.t ............... 9/? C:\dev\git\git-subrepo\lib\git-subrepo: line 886: subrepo:merge-base: command not found
test/status.t ............... 10/? #   Failed test 'subrepo status (diverged) output is correct'
#   at test/status.t line 99.
--- /tmp/want-14064     2016-03-31 16:46:53.084788500 +1100
+++ /tmp/got-14064      2016-03-31 16:46:53.083787700 +1100
@@ -1,5 +1,4 @@
 Git subrepo 'bar':
-  Subrepo and upstream have diverged.
-    (use 'git subrepo pull' to merge the remote subrepo into yours)
+  Status not available: no common ancestor found

 See also: git subrepo show ...
# Tests were run but no plan was declared.
test/status.t ............... Failed 4/10 subtests
test/submodule.t ............ ok

Test Summary Report
-------------------
test/status.t             (Wstat: 0 Tests: 10 Failed: 4)
  Failed tests:  5-6, 8, 10
```

**Comment by stsquared99** [comment]
Ah, I see. It depends whether this sort of change should be rolled out now, or after #142. Up to you guys. In either case, I can rewrite the command to work with the issue/142 branch.

The ref you are missing is the subrepo branch, hence the "(use 'git subrepo branch' to update)" message. I guess once merge-base is removed we won't need to rely on the branch anymore to compare local vs remote...

Thanks

**Comment by robe070** [comment]
Couldn't the branch ref be derived from the branch in `.gitrepo`?
I believe I have performed a `subrepo clean` on this repo. Shouldn't the command continue to work after a `clean`?
Or is this entirely because of issue/142 code?

**Comment by stsquared99** [comment]
The command as is requires the presence of the refs/heads/subrepo/lansa/imports/DEMOAPP or refs/subrepo/lansa/imports/DEMOAPP/branch ref. This would in fact be missing if you just performed a clean. I did not have it automatically create/update the branch when running 'status', because that can be slow in larger repos. I am open to input though.
Thanks

**Pull request closed without merging**
