### PR TITLE
Fixes Travis CI build. It was not checking out a branch.

### PR DESCRIPTION
**Pull request by mupdt**
The command in `.travis.yml` that is supposed to checkout the branch did not actually check out the branch.

### CODE REVIEW

**Comment by mupdt** [comment]
I accidentally deleted my branch. Reopening.

**Comment by mupdt** [comment]
@grimmySwe: Hey grimmy, could you check out this PR. It merges into the `release/0.4.0` branch. It looks like you're maintaining that branch.

**Comment by grimmySwe** [comment]
@mupdt Hi, for me it looks ok, although I don't know if @ingydotnet had any special thoughts with the restrictions?

**Comment by mupdt** [comment]
@ingydotnet: ping

**Comment by ingydotnet** [comment]
Can you target this PR against master? The `release/0.4.0` branch has now been merged.

**Comment by mupdt** [comment]
> Can you target this PR against master? The `release/0.4.0` branch has now been merged.

Done 👍

**Comment by admorgan** [comment]
Sorry about the false hope, did the wrong thing and it is getting fixed now.

**Pull request merged**
