### PR TITLE
Fix error "fatal: Not a valid object name: ''."

### PR DESCRIPTION
**Pull request by DanielBauten**
# Problem

In case there are no (relevant) commits (e.g. directly after `git subrepo push`) which cause `subrepo:branch()` (i.e. on `git subrepo pull <subrepo>`) to fail with an git error message

> git-subrepo: Command failed: 'git branch subrepo/\<subrepo\> '.
> fatal: Not a valid object name: ''.

See issues #348, #350 and #424.

# Cause

This is because second parameter to `git branch` is an empty string as variable `prev_commit` has not been set. Thus, [branch creation](https://github.com/ingydotnet/git-subrepo/blob/a04d8c2e55c31931d66b5c92ef6d4fe4c59e3226/lib/git-subrepo#L789) fails in that case.

# Solution

To create the subrepo branch, nevertheless, it can be created on the cloned/pulled commit from `.gitrepo` file (per variable `subrepo_commit`) as there have not been any relevant changes.
Furthermore – to avoid unnecessary large range on the subsequent [call of `git filter-branch`](https://github.com/ingydotnet/git-subrepo/blob/a04d8c2e55c31931d66b5c92ef6d4fe4c59e3226/lib/git-subrepo#L800) – variable `first_gitrepo_commit` should be neutralized with `subrepo_commit` as well, so that variable `filter` results in an empty revision range.

### CODE REVIEW

**Comment by admorgan** [comment]
Would you be willing to add some tests for this?

**Comment by admorgan** [comment]
If this blindly "fixes" the issues you linked I think that could be a problem. Your example of a pull after a push is desirable, but when the ancestry has changed I feel we should acknowledge that there is a potential for your code not being what you expect. I have to dive deeper, but I believe it would not effect the included issues because we would fail before we reach this code due to the SHA not existing. @ingydotnet I would like you to look at this one if you have some time.

Overall thank you, this has been a thorn in my side. I have another favor to ask. We are currently working on the release/0.4.2 branch would you mind applying these patches there instead?

**Comment by DanielBauten** [comment]
> Would you be willing to add some tests for this?

We were able to recreate the problem very well during the corrections to #497 and therefore believe that it was not just blindly fixed the issue linked. However, we have only been working with sub-repo for a few weeks and therefore have no experience in how to write suitable tests.

So – if @ingydotnet sees the need for this – it would be great if a more experienced developer could write some suitable tests.

**Comment by blaggacao** [comment]
I think I hit this after a sqash merge of a feature branch where I did git subrepo on the feature branch. Does that sound plausible?

**Comment by DanielBauten** [comment]
> I think I hit this after a sqash merge of a feature branch where I did git subrepo on the feature branch. Does that sound plausible?

Sounds plausible. If it reproducable in your case, perhaps you can check wether our fix is applicable on your situation.

**Comment by natew** [comment]
Is there a way to fix this manually for now?

**Comment by admorgan** [comment]
Modify the parent sha in your .gitrepo file to be the previous commit in your repo.

**Comment by natew** [comment]
Unfortunately that seems to "squash" all the changes across a bunch of commits into one... We work on branches that rebase off master, then merge, but it seems every time i have to update the SHA to the latest, so all intermediate messages are being removed.

**Comment by dwettstein** [comment]
Probably this PR refers to https://github.com/ingydotnet/git-subrepo/issues/503 and https://github.com/ingydotnet/git-subrepo/issues/532 as well.

**Comment by jameswalmsley** [comment]
Can we merge this PR?

**Comment by jcalfee** [comment]
What SHA do I use for the parent?  Is SHA easier to get from the client or the server?  Maybe I should git log on the subrepo folder to find this?

**Comment by admorgan** [comment]
I have been working with this patch, and have found a number of paths that cause issues with regenerating the branch. I am addressing this through UI improvements and better error messaging instead of automatic regeneration for these reasons.

**Pull request closed without merging**
